### ISSUE TITLE
Do we need a data filter in cvProcessData.m ?

### ISSUE THREAD

**Issue by refisch** [clemenskreutz/CVID-19-modelling#5]
From my point of view all the data filtering should happen in `cvDataSettingExecution`.

`cvProcessData('>=20')` will for flux and cumulative data censor the data differently. Differing results might therefore be induced by this function. Can we scrap the function altogether?

**Comment by clemenskreutz** [comment]
Yes, you are right. Let' remove the call of this function.

Nevertheless, let's keep the function since it would be the right place for "processing", adjusting or distorting the data if that would be intended in future.
