### ISSUE TITLE
initial values

### ISSUE THREAD

**Issue by refisch** [clemenskreutz/CVID-19-modelling#6]
The time point zero (t=0) describes either 
* the first data point recorded by Johns-Hopkins-University OR
* the sum(first data points) > threshold, with threshold being 20 or 100.
The latter case means that some kind of dynamics has already taken place, therefore I am wondering whether the condition
```
init_Exposed    "0"
```
and to some lesser extend also 
```
init_Recovered   "0"
init_Dead "0"
```
in the model.def file of the SEIR are still valid.

The linear chains of the more complex models need also some considerations here, I guess... What do you think?

**Comment by refisch** [comment]
Thinking about it, I think this might be a source for only a minor error.
On the other hand, the sources for minor errors might add up, so I keep the issue open for now.

**Comment by clemenskreutz** [comment]
After this discussion we chose approximate intial values for the "exposed" states that were derived from S(0) and I(0) under steady state assumptions.
