### ISSUE TITLE
initial_Susceptibles

### ISSUE THREAD

**Issue by refisch** [clemenskreutz/CVID-19-modelling#7]
Currently upper bound of parameter initial_Susceptibles can be bigger than the known population of the countries: 
```
arSetPars('init_Susceptibles', log10(82800000), 1, 1, log10(82800000/10), log10(82800000*10), 1, log10(82800000),1);
```
This does not seem to coincide with reality. Instead, we could do:
```
arSetPars('init_Susceptibles', log10(82800000), 1, 1, log10(82800000/100), log10(82800000), 1, log10(82800000),1);
```

**Comment by clemenskreutz** [comment]
My first idea was to consider knowledge about the population as prior and allow that this parameters is fitted differently. This might help to (indirectly) account for simplifications of the model (e.g. spatial effects) and for being able to describe the data. The outcome would be "We can only explain the data by assuming an increase (or decrease) of the EFFECTIVE population size". 

However, I'm also okay with using the real popuation as an upper bound. It prevents overestimation of peaks ...
